### ISSUE TITLE
TODOs for country-specific analysis across systems

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/DMsan#21]
I'm thinking as I type and also give you @haclohman an idea of what needs to be done next. I currently have managed to pull the different systems in a same script and made sure consistent parameter values are used in simulation, but I ran into this problem https://github.com/QSD-Group/EXPOsan/issues/24 and need to take care of it first.

So next steps
- [x] Resolve https://github.com/QSD-Group/EXPOsan/issues/24, and hopefully we'll be able to get the scores for MCDA
- [x] Update [uncertainty_sensitivity.py](https://github.com/QSD-Group/DMsan/blob/main/dmsan/comparison/uncertainty_sensitivity.py) for MCDA under uncertainty, I think we've got the uncertainty part figured out, but I stopped at sensitivity since I wanted to make sure that consistent parameter values are used and that led to the whole restructuring of the systems in EXPOsan, but now we should pick this up, I'll just add Spearman for now, I think from bwaise's experience KS didn't really provide much new info, we can add it later if we want to explore.
- [x] If there's any analyses from bwaise you want to do, we can add those, but I'll want to develop generalizable functions instead of copying bwaise's codes and paste to another module for easier management and better consistency

**Comment by haclohman** [comment]
That all sounds good! I think Spearman should be good for now. I'll spend some time outlining my manuscript and planning the types of results I want to include. Also, if you have any ideas for how we could look at results/trends across locations let me know! I think discussing the differences in indicator weights across locations could be interesting to talk about and then the differences in which technologies are being selected across countries within a criteria weight scenario could be cool.

Let me know what you'd like me to do vs you for this to do list and the updates for the country_specific.py script.

**Comment by yalinli2** [comment]
@haclohman The first one is done as discussed d5c1960e42a54ff8c25a52c24b79a4e7fc984789!

Finally all of the six systems within the three modules can be run together (shedding proud tears). It took ~2 min for 5 countries for N=20, probably under 2 hrs with N=1,000, 5 countries. I'd think 1,000 is enough, in the past I got about the same results for N=1,000 vs. N=5,000 from the bwaise module, you can try with 1 module, 1 country with a larger N if want to be safe.

In the future if you want to add more countries, you can update the [`country_specific_inputs.csv`](https://github.com/QSD-Group/DMsan/blob/main/dmsan/comparison/data/country_specific_inputs.csv) data sheet, columns are the countries/scenarios and rows are the parameters, if you want to add a parameter, don't forget to add the parameter in the `country_specific.py` module in EXPOsan.

I might not have time for Task 2 over the weekend, I'll try to find some time after Tuesday to get it done.

For Task 3 I'll aim for getting the X'mas tree figures, which should be pretty quick once 2 is done. For Spearman I think the [bar charts](https://github.com/QSD-Group/DMsan/blob/main/dmsan/bwaise/figures/Spearman_rho_A.png) @joyxyz1994 made are pretty cool, so maybe ask her to help add the that when I finish this issue.

In the meantime I think you can focus on:
1. Check if the results I currently got make sense, e.g., cost are very different across countries, but not environmental impacts, probably because we don't have a lot of country-specific data for them, or there could be bugs...
2. Gather data for other countries you want

Let me know suggestions!

**Comment by haclohman** [comment]
Awesome! Thank you so much!! I will check the results tomorrow to make sure everything looks ok. The only country-specific part of the LCA is related to the energy emissions. I'll make sure the changes related to energy source are being correctly accounted for.

**Comment by haclohman** [comment]
I checked the country-specific results for the baseline metrics, and I think they look ok. The only thing that changes by country for the LCA is the electricity CF. I did a back of the envelope calc to make sure the results look ok for electricity and they look good. Reclaimer model B and NEWgen model B both are solar energy so their emissions will be unchanged across the countries since there is no electricity input.

Right now we only have one global CF for each material - I could go back into SimaPro and gather the country-specific values available for the list of materials to see more differences across countries in LCA.

**Comment by yalinli2** [comment]
OK sounds good to me!

**Comment by yalinli2** [comment]
I updated the uncertainty analysis in the comparison module, I also wrote the code for the sensitivity analyses but unsure how we want to save the results, then I became unsure of the use of the sensitivity analysis...

@haclohman , when you have time, maybe it'll be good if you can look at the uncertainty results and think of what figures you want, then we can discuss with @joyxyz1994 if/how we want to run/plot the sensitivity analysis, thanks!

**Comment by yalinli2** [comment]
OK I added some initial figures (https://github.com/QSD-Group/DMsan/commit/0853bf5fd8f52a98491f5402af76677fb44835b4) for quick visualization (in the [/figures](https://github.com/QSD-Group/DMsan/tree/main/dmsan/comparison/figures) dir), aside from the sensitivity analysis since I'm not sure if it makes sense to do the sensitivity between system simulation uncertain parameters and the performance score without considering the global/indicator weights

but otherwise the results look interesting at the first glance - Biogenic Refinery and Reclaimer are neck-to-neck and the winner depends on the country, though I forgot whether I cached the simulation results before or after you fix the price for the Reclaimer module, you might want to check and fix all the bugs, re-simulate the system with use a larger N (I just used 20)

running MCDA (mcda.py) took 7 min for 5 countries, N=20, 100 weight scenarios, MCDA itself took almost no time, it's all because of Spearman (needs to do it for every weight scenario),  I might poke around and see what's dragging this if I remember...

**Comment by yalinli2** [comment]
Adding some notes following our discussions:
1. There's no issue with Spearman now since we'll only do that between uncertain parameters and indicator scores, not the performance scores
2. I've opened another two issues with very brief description on what's needs to be done, so I'll close this
